### PR TITLE
Updated README.txt with configure.exe location

### PR DESCRIPTION
**Pull request by ogre**
Before running `configure.exe` make sure it's copied into `VisualMagick\configure\configure.exe` location, otherwise it will generate empty MSVC solution.

### CODE REVIEW

**Comment by dlemstra** [comment]
I think it would be better to add a Readme.md here instead and point to the instructions in the ImageMagick-Windows repository instead. Would you be willing to make this change @ogre?

**Comment by ogre** [comment]
Hello @dlemstra 
I am not sure what you ask?
There was no README.md originally in this repo, just a README.txt that already points to full building instructions. I merely added a note on required configure.exe location.
I'm willing to help with this but would need some directions.

**Comment by dlemstra** [comment]
I would like to replace the `readme.txt` with a `readme.md` file and only point to the instructions in the `ImageMagick-Windows` project.

**Comment by ogre** [comment]
Let me know if this satisfies you.

**Pull request merged**
